#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void wheel(int l, int r, int t, bool accelerate=true){
	int oldL = motor[motorL];
	int oldR = motor[motorR];
	int deltaL = l-oldL;//it's an "L"
	int deltaR = r-oldR;
	for (int i = 0; i < 10; ++i)
	{
		if(!accelerate)break;
		oldL+=(deltaL/10);
		oldR+=(deltaR/10);
		motor[motorL]=oldL/1;//it's an "L"
		motor[motorR]=oldR/1;
		wait1Msec(20);
	}
	motor[motorL]=l;//it's an "L"
	motor[motorR]=r;
	wait1Msec(t);
	return;
}

int speed=100;
int target=5760;

task main()
{
	nMotorEncoder[motorR] = 0;
	for(int i=-2;i!=256;i*=(-2)){
		wheel(0,speed,0)
		if(speed>0)while(nMotorEncoder[motorR]<target){}
		if(speed<0)while(nMotorEncoder[motorR]>target){}
		motor[motorR] = 0;
		//wait1Msec(200);
		writeDebugStreamLine("%d", nMotorEncoder[motorR]);
		speed=100/i;
	}
}
