#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorUsed,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorUnused,   tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[motorUsed] = 0;

	while(nMotorEncoder[motorUsed] < 1024){
		nxtDisplayCenteredTextLine(3, "%d", nMotorEncoder[motorUsed]);
		motor[motorUsed] = 100;
	}
	motor[motorUsed] = 0;
}
