#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     latchMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     armMotor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorR,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int threshold = 3;
int armThreshold = 3;

int MotorValue(float joyInput){
	float tInputV = abs(joyInput);
	float tMotorValue = pow(tInputV, (tInputV / 128));
	return tMotorValue;
}

task main()
{
	while(true){

		getJoystickSettings(joystick);

		//Wheels
		if(abs(joystick.joy1_y1) > threshold){
			if(joystick.joy1_y1 > 0){
				motor[motorL] = MotorValue(joystick.joy1_y1);
				nxtDisplayCenteredTextLine(3, "%d, %d", MotorValue(joystick.joy1_y1), MotorValue(joystick.joy1_y2);
			}else{
				motor[motorL] = -MotorValue(joystick.joy1_y1);
				nxtDisplayCenteredTextLine(3, "%d, %d", MotorValue(joystick.joy1_y1), MotorValue(joystick.joy1_y2);
			}
		}else{
			motor[motorL] = 0;
		}
		if(abs(joystick.joy1_y2) > threshold){
			if(joystick.joy1_y2 > 0){
				motor[motorR] = MotorValue(joystick.joy1_y2);
			}else{
				motor[motorR] = -MotorValue(joystick.joy1_y2);
			}
		}else{
			motor[motorR] = 0;
		}


		//Arm
		if(abs(joystick.joy2_y1) < armThreshold){
			motor[armMotor] = 0;
		}else{
			if(joystick.joy2_y1 < 0){
				motor[armMotor] = abs(joystick.joy2_y1 * 0.35);
			}else{
				motor[armMotor] = -joystick.joy2_y1 * 0.35;
			}
		}


		//Latcher
		if(abs(joystick.joy2_x2) < armThreshold){
			motor[latchMotor] = 0;
		}else{
			if(joystick.joy2_x2 < 0){
				motor[latchMotor] = abs(joystick.joy2_x2 * 0.17);
			}else{
				motor[latchMotor] = -joystick.joy2_x2 * 0.17;
			}
		}
	}
}
