#pragma config(Hubs,  S3, HTMotor,  none,     none,     none)
#pragma config(Sensor, S3,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S3_C1_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S3_C1_2,     motorR,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	motor[motorL] = 100;
	motor[motorR] = 100;
	wait1Msec(1000);
	motor[motorL] = -100;
	motor[motorR] = -100;
	wait1Msec(1000);
}
