#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     armUp1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     armUp2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     armFlip1,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     backArm,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Bucket,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int threshold = 3;                                           //threshold
float power = 2.25;
int a=0;

int MotorValue(float joyInput){                              //exponential function
	float tInputV = abs(joyInput);
	float tMotorValue = pow(tInputV, power);
	tMotorValue *= (128/pow(128, power));
	return tMotorValue;
}
void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}
task main()
{
	initializeRobot();
	waitForStart();
	getJoystickSettings(joystick);  															//get joystick settings
	while(true){

		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/driving/-/-/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//


		if(joy1Btn(8)==1)a++;                                       //inverse driving button

		//Normal Driving
		if (a%2==0){

			//Left Stick Control
			if(abs(joystick.joy1_y1) > threshold){
				if(joystick.joy1_y1 > 0){
					motor[motorL] = MotorValue(joystick.joy1_y1);
					}else{
					motor[motorL] = -MotorValue(joystick.joy1_y1);
				}
				}else{
				motor[motorL] = 0;
			}

			//Right Stick Control
			if(abs(joystick.joy1_y2) > threshold){
				if(joystick.joy1_y2 > 0){
					motor[motorR] = MotorValue(joystick.joy1_y2);
					}else{
					motor[motorR] = -MotorValue(joystick.joy1_y2);
				}
				}else{
				motor[motorR] = 0;
			}

			//Under Inversed Driving
			}else{

			//Right Stick Control
			if(abs(joystick.joy1_y2) > threshold){
				if(joystick.joy1_y2 > 0){
					motor[motorL] = -MotorValue(joystick.joy1_y2);
					}else{
					motor[motorL] = MotorValue(joystick.joy1_y2);
				}
				}else{
				motor[motorL] = 0;
			}
			//Left Stick Control
			if(abs(joystick.joy1_y1) > threshold){
				if(joystick.joy1_y1 > 0){
					motor[motorR] = -MotorValue(joystick.joy1_y1);
					}else{
					motor[motorR] = MotorValue(joystick.joy1_y1);
				}
				}else{
				motor[motorR] = 0;
			}
		}

		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/Arm Up&Down/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//

		if(abs(joystick.joy2_y1) > threshold){
			if(joystick.joy2_y1 > 0){
				motor[armUp1] = MotorValue(joystick.joy2_y1);
				motor[armUp2] = MotorValue(joystick.joy2_y1);
				}else{
				motor[armUp1] = -MotorValue(joystick.joy2_y1);
				motor[armUp2] = -MotorValue(joystick.joy2_y1);
			}
			}else{
			motor[armUp1] = 0;                                    //stop arm from moving
			motor[armUp2] = 0;
		}

		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/Bucket Flip/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//

		if(abs(joystick.joy2_y2) > threshold){
			if(joystick.joy2_y2 > 0){
				motor[armFlip1] = 0.1*MotorValue(joystick.joy2_y2);

				}else{
				motor[armFlip1] = -0.1*MotorValue(joystick.joy2_y2);

			}
			}else{                                                  //stop arm from moving
			motor[armFlip1] = 0;

		}


		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/Back Arm /-/-/-/-/-/-/-//
		//-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-//

		if(joy2Btn(5)==1){                                     //put backarm up
			motor[backArm]=-10;
		}else if(joy2Btn(6)==1){
			motor[backArm]=20;                                    //put backarm down
		}else{
		  motor[backArm]=0;
		}

		///////////////////////////////////////////
		//////////Bucket Intake&Output/////////////
		///////////////////////////////////////////

		if(joy1Btn(5)==1){                                     //intake balls
			motor[A]=100;
			motor[B]=100;
		}else if(joy1Btn(6)==1){                                     //output balls
			motor[A]=-100;
			motor[B]=-100;
		}else{
			motor[A]=0;
			motor[B]=0;
		}
	}
}
