#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S4,     IRSeeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     armUp1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     armUp2,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     motorR,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     armFlip1,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     backArm,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorJ,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     Bucket,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "C:\Users\dhou\Desktop\rdpartyrobotcdr-3.3.1\drivers\common.h"
//#include "C:\Users\dhou\Desktop\rdpartyrobotcdr-3.3.1\drivers\hitechnic-irseeker-v2.h"
int state=0b00000000;
int mode = 1;

int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
string messagelol="going straight...";

void wheel(int l, int r, int t){
	int oldL = motor[motorL];
	int oldR = motor[motorR];
	int deltaL = l-oldL;//it's an "L"
	int deltaR = r-oldR;
	for (int i = 0; i < 10; ++i)
	{
		oldL+=(deltaL/10);
		oldR+=(deltaR/10);
		motor[motorL]=oldL/1;//it's an "L"
		motor[motorR]=oldR/1;
		wait1Msec(20);
	}
	motor[motorL]=l;//it's an "L"
	motor[motorR]=r;
	wait1Msec(t);
	return;
}

int getOffRamp(){
	wheel(20,20,2750);
	wheel(-10,10,1000);
	wheel(20,20,1500);
	return 0;
}

void homeInOnBeacon(){
	int angle=5;
	while(true){
		//HTIRS2readAllDCStrength(IRseeker, dcS1, dcS2, dcS3, dcS4, dcS5);
		angle=Sensorvalue[IRseeker];
		if(angle < 5 & angle > 0){
			messagelol="turning left...";
			wheel(0,20,0);
		}
		if(angle == 5){
			messagelol="going straight.";
			wheel(10,10,0);
		}
		if(angle > 5){
			messagelol="turning right.";
			wheel(20,0,0);
		}
		if(angle == 0){
			messagelol="No signal detected.";
			wheel(-10,10,0);
		}
		/*if(dcS3 > 170){
			wheel(0,0);
			return 0;
		}*/
		nxtDisplayCenteredTextLine(3,"%d, %s",angle,messagelol);
		//nxtDisplayCenteredTextLine(4,"%s, %d","Channel 3:",dcS3);
	}
}

int determinePos(){
	wait1Msec(1000);
	while(true){
		if(SensorValue[IRSeeker]==0|SensorValue[IRSeeker]==7){
			return 1;
		}else if(SensorValue[IRSeeker]==5){
			return 2;
		}
	}
}

void kickStand(int x){
	if(x==1){
		wheel(40,40,500);
		wheel(-50,50,800);
	}else if(x==2){
		wheel(30,30,500);
		wheel(70,-70,2000);
		wheel(30,30,600);
		wheel(-70,70,1000);
		wheel(75,75,1600);
	}else{
		determinePos();
	}
}

task main(){
	//getOffRamp();
	kickStand(determinePos());
}
