#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int state=0b00000000;
int mode = 1;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
string messagelol="going straight...";
#include "C:\Users\dhou\Desktop\rdpartyrobotcdr-3.3.1\drivers\hitechnic-irseeker-v2.h"

void wheel(int l, int r){
	motor[motorL]=l;//it's an "L"
	motor[motorR]=r;
	return;
}

int homeInOnBeacon(){
	int angle=5;
	while(true){
		if(angle < 1){
			messagelol="turning left...";
			wheel(0,20);
		}
		if(angle == 5){
			messagelol="going straight.";
			wheel(10,10);
		}
		if(angle > 5){
			messagelol="turning right.";
			wheel(20,0);
		}
		if(angle == 0){
			messagelol="No signal detected.";
			wheel(-10,10);
		}
		nxtDisplayCenteredTextLine(3,"%d, %s",angle,messagelol);
		HTIRS2readAllDCStrength(IRseeker, dcS1, dcS2, dcS3, dcS4, dcS5);
		angle=SensorValue[IRseeker];
		return 0;
	}
}

task main(){
	wait(1000);
	while(true){
		nxtDisplayCenteredTextLine(3,"%d, %s",sensorvalue[IRseeker],messagelol);
	}
}
