#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "C:\Users\dhou\Desktop\rdpartyrobotcdr-3.3.1\drivers\common.h"
//#include "C:\Users\dhou\Desktop\rdpartyrobotcdr-3.3.1\drivers\hitechnic-irseeker-v2.h"
int mode = 1;
int dcS1, dcS2, dcS3, dcS4, dcS5 = 0;
string messagelol="going straight...";
int recording[1024];
int recording2[512]
int indexNum = 0;
int sampleRate = 100; //in ms

void wheel(int l, int r){
	int oldL = motor[motorL];
	int oldR = motor[motorR];
	int deltaL = l-oldL;//it's an "L"
	int deltaR = r-oldR;
	for (int i = 0; i < 10; ++i)
	{
		oldL+=(deltaL/10);
		oldR+=(deltaR/10);
		motor[motorL]=oldL;//it's an "L"
		motor[motorR]=oldR;
		wait1Msec(20);
	}
	motor[motorL]=l;//it's an "L"
	motor[motorR]=r;
	return;
}

void record(int t){
	int samples = t/sampleRate;
	for(int i=0; i<samples;i++){
		recording[indexNum]=Sensorvalue[IRseeker];
		indexNum++;
		wait1Msec(sampleRate);
	}
}

void record2(int t){
	ClearTimer(T4)
	int dirs[2]={0,0};
	int j = 0;
	while(time1[T4]<t){
		dirs[0]=dirs[1];
		dirs[1]=Sensorvalue[IRseeker];
		if(dirs[1]!=dirs[0]){
			recording2[j]=dirs[0];
			recording2[j+1]=dirs[1];
			recording2[j+2]=time1[T4];
			j+=3;
		}
	}
}

int getOffRamp(){
	wheel(20,20);
	record2(3000);
	wheel(0,0);
	return 0;
}

void homeInOnBeacon(){
	int angle=5;
	while(true){
		//HTIRS2readAllDCStrength(IRseeker, dcS1, dcS2, dcS3, dcS4, dcS5);
		angle=Sensorvalue[IRseeker];
		if(angle < 5 & angle > 0){
			messagelol="turning left...";
			wheel(0,20);
		}
		if(angle == 5){
			messagelol="going straight.";
			wheel(10,10);
		}
		if(angle > 5){
			messagelol="turning right.";
			wheel(20,0);
		}
		if(angle == 0){
			messagelol="No signal detected.";
			wheel(-10,10);
		}
		/*if(dcS3 > 170){
			wheel(0,0);
			return 0;
		}*/
		nxtDisplayCenteredTextLine(3,"%d, %s",angle,messagelol);
		//nxtDisplayCenteredTextLine(4,"%s, %d","Channel 3:",dcS3);
	}
}

void reportData(){
	while(true){
		if(nNxtButtonPressed>-1){
			int lineNum = 1;
			int x,y;
			for(int i=0; i<=indexNum; i++){


			}
		}
	}
}

void reportData2(){
	int i=0;
	int j=0;
	while(true){
<<<<<<< Updated upstream
		if(nNxtButtonPressed==1){
			while(true){
				if(j>7){
					j=0;
					wait1Msec(5000);
				}
				if(recording2[i+2]==0&recording2[i+5]==0){
					nxtDisplayCenteredTextLine(j,"***end***");
					wait1Msec(2000);
					return;
				}
				nxtDisplayCenteredTextLine(j,"%d to %d: %1.3f secs",recording2[i],recording2[i+1],(float)(recording2[i+\

				2]/1000.000));
				i+=3;
				j++;
			}
=======
		if(j>7){
			j=0;
			wait1Msec[5000];
		}
		if(recording2[i+2]==0&recording2[i+5]==0){
			nxtDisplayCenteredTextLine(j,"***end***angle");
			return;
>>>>>>> Stashed changes
		}
	}
}

task main(){
	getOffRamp();
	reportData2();
	while(true){

	}
}
