#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     armUp1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     armUp2,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int threshold = 3;                                           //threshold
float power = 2.25;

int MotorValue(float joyInput){                              //exponential function
	float tInputV = abs(joyInput);
	float tMotorValue = pow(tInputV, power);
	tMotorValue *= (128/pow(128, power));
	return tMotorValue;
}

task main()
{
	getJoystickSettings(joystick);
	while(true){
	if(abs(joystick.joy1_y1) > threshold){
		if(joystick.joy1_y1 > 0){
			motor[armUp1] = MotorValue(joystick.joy1_y1);
			motor[armUp2] = 0.65*MotorValue(joystick.joy1_y1);
			}else{
			motor[armUp1] = -MotorValue(joystick.joy1_y1);
			motor[armUp2] = -0.8*MotorValue(joystick.joy1_y1);
		}
	}else{
		motor[armUp1] = 0;                                    //stop arm from moving
		motor[armUp2] = 0;
	}
 }
}
