#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchUp,        sensorTouch)
#pragma config(Sensor, S3,     touchDown,      sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motor1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor2,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true){
    if (SensorValue[touchUp]==1){
    	motor[motor1]= 100;
    	motor[motor1]= 100;
    }
    else if (SensorValue[touchDown]==1){
    	motor[motor1]= -100;
    	motor[motor1]= -100;
    }
    if (SensorValue[touchDown]==0&&SensorValue[touchUp]==0){
    	motor[motor1]= 0;
    	motor[motor1]= 0;
    }
	}
}
