#pragma config(Motor,  motorA,          A,             tmotorNXT, PIDControl, reversed, encoder)
#pragma config(Motor,  motorB,          B,             tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int threshold = 3;                                           //threshold
float power = 2.25;
int a=0;

int MotorValue(float joyInput){                              //exponential function
	float tInputV = abs(joyInput);
	float tMotorValue = pow(tInputV, power);
	tMotorValue *= (128/pow(128, power));
	return tMotorValue;
}
void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}
task main()
{
	initializeRobot();
	waitForStart();
	getJoystickSettings(joystick);  															//get joystick settings
	while(true){
		if(abs(joystick.joy1_y1) > threshold){
			if(joystick.joy1_y1 > 0){
				motor[A] = MotorValue(joystick.joy1_y1);
				motor[B] = MotorValue(joystick.joy1_y1);
				}else{
				motor[A] = -MotorValue(joystick.joy1_y1);
				motor[B] = -MotorValue(joystick.joy1_y1);
			}
			}else{
			motor[A] = 0;
			motor[B] = 0;
		}
  }
}
