#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IRseeker,       sensorNone)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int state = 0;


task main()
{
	while (state==0){
		motor[motorL] = 5;
		motor[motorR] = 5;
   nxtDisplayCenteredBigTextLine(3,"%d",sensorvalue(IRseeker));
		if(SensorValue[IRseeker] == 2){
			state++;
		}

	}

	while (state==1){
		motor[motorL] = -10;
		motor[motorR] = 10;
  nxtDisplayCenteredBigTextLine(3,"%d",sensorvalue(IRseeker));
		if(SensorValue[IRseeker] == 5){
			state++;
		}
	}

	while (state==2){
	 motor[motorL] = 0;
	 motor[motorR] = 0;
	nxtDisplayCenteredBigTextLine(3,"%d",sensorvalue(IRseeker));
	/*	motor[motorL] = 50;
		motor[motorR] = 50;

		if(SensorValue[IRseeker] != 5){
			state++;
		}
	}

	while (state==3){
		motor[motorL] = 0;
		motor[motorR] = 0;

		break;*/


	}
}
