#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorMatrix, openLoop, reversed, driveLeft)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorMatrix, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int gOffset,value=0;
float turned=0
float multiplier=2162.0/1573.0;
long lastTime=0;

void progressBar(int l,int x, int y){
	char a,b,c,d,e,f,g,h,i,j,k,ll,m,n=' ';
	int prog = x/(y/15);
	switch(prog){
		case 15:
		case 14:
			n='=';
		case 13:
			m='=';
		case 12:
			ll='=';
		case 11:
			k='=';
		case 10:
			j='=';
		case 9:
			i='=';
		case 8:
			h='=';
		case 7:
			g='=';
		case 6:
			f='=';
		case 5:
			e='=';
		case 4:
			d='=';
		case 3:
			c='=';
		case 2:
			b='=';
		case 1:
			a='=';
	}
	nxtDisplayTextLine(l,"|%c%c%c%c%c%c%c%c%c%c%c%c%c%c|",a,b,c,d,e,f,g,h,i,j,k,ll,m,n);
}

void calibrateGyro(int samples){
	nxtDisplayCenteredTextLine(3,"Calibrating...");
	gOffset=0;
	for(int i=0; i<samples; i++){
		gOffset+=SensorValue[Gyro];
		wait1Msec(4);
		progressBar(4,i,samples);
	}
	gOffset/=samples;
}

task main(){
	clearTimer(T4);
	calibrateGyro(256);
	while(true){
		value = SensorValue[Gyro];
		if(abs(value)<2)value=-gOffset;
		turned+=(float)(value-gOffset)*720.0*(float)(time1(T4)-lastTime)*multiplier/1023000.0;
		lastTime=time1(T4);
		nxtDisplayCenteredBigTextLine(0,"%d",value);
		nxtDisplayCenteredBigTextLine(2,"%d",(value-gOffset));
		nxtDisplayCenteredBigTextLine(4,"%d",turned);
		wait1Msec(5);
	}
}

//void gturn(int x,int v){//resolution of 0.01 degrees, and input in numbers of 0.01 degrees
//	int turned=0;
//	int lastTime=0;
//	calibrateGyro(128);
//	if(x<0){
//		wheel(-v,v,0);
//		}else if(x>0){
//		wheel(v,-v,0);
//		}else{
//		return;
//	}
//	clearTimer(T4);
//	while(abs(turned)<abs(x)){
//		turned+=(SensorValue[Gyro]-gOffset)*36000*time1(T4)/1024000;
//		clearTimer(T4);
//		nxtDisplayCenteredBigTextLine(0,"%d",x);
//		nxtDisplayCenteredBigTextLine(2,"%d",turned);
//	}
//	return;
//}
