#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     IRseeker,       sensorHiTechnicIRSeeker1200)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

string messagelol="going straight...";
task main(){
	while(sensorvalue[IRseeker]!=1){
		string messagelol="going straight...";
   	nxtDisplayCenteredTextLine(3,"%d, %s",sensorvalue[IRseeker],messagelol);
		}

	while(true){
		if(SensorValue[IRseeker] == 1){
			messagelol="turning left...";
		}
		if(SensorValue[IRseeker] == 5){
			messagelol="going straight.";
		}
		if(SensorValue[IRseeker] > 5){
			messagelol="turning right.";
		}
		if(SensorValue[IRseeker] == 0){
			messagelol="No signal detected.";
		}
		nxtDisplayCenteredTextLine(3,"%d, %s",sensorvalue[IRseeker],messagelol);
	}
}

void lol(){
	return;
}
