#pragma config(Sensor, S1,     seeker1,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S2,     seeker2,        sensorHiTechnicIRSeeker600)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "C:\Users\dhou\Desktop\rdpartyrobotcdr-3.3.1\drivers\common.h"
#include "C:\Users\dhou\Desktop\rdpartyrobotcdr-3.3.1\drivers\hitechnic-irseeker-v2.h"

task main()
{
	while(true){
//		nxtDisplayCenteredTextLine(3, "%d, %d", SensorValue[seeker1], SensorValue[seeker2]);
		nxtDisplayCenteredTextLine(3, "Sensor 1: %d", SensorValue[seeker1]);
		nxtDisplayCenteredTextLine(5, "Sensor 2: %d", SensorValue[seeker2]);

	}
}
