#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorL,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorR,        tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S2_C1_1,    servoL,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    servoR,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

int threshold = 3;                                           //threshold
float power = 2.25;

int MotorValue(float joyInput){                              //exponential function
	float tInputV = abs(joyInput);
	float tMotorValue = pow(tInputV, power);
	tMotorValue *= (128/pow(128, power));
	return tMotorValue;
}
void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}
task main()
{
	initializeRobot();
	waitForStart();
	getJoystickSettings(joystick);  															//get joystick settings
	while(true){
		if(abs(joystick.joy1_y1) > threshold){
			if(joystick.joy1_y1 > 0){
				motor[motorL] = MotorValue(joystick.joy1_y1);
				}else{
				motor[motorL] = -MotorValue(joystick.joy1_y1);
			}
			}else{
			motor[motorL] = 0;
		}

		if(abs(joystick.joy1_y2) > threshold){
			if(joystick.joy1_y2 > 0){
				motor[motorR] = MotorValue(joystick.joy1_y2);
				}else{
				motor[motorR] = -MotorValue(joystick.joy1_y2);
			}
			}else{
			motor[motorR] = 0;
		}

		if(abs(joystick.joy2_y1) > threshold){
			servo[servoL]=128+joystick.joy2_y1;}
			else{
				servo[servoL] = 128;
			}

				if(abs(joystick.joy2_y2) > threshold){
			servo[servoL]=128+joystick.joy2_y2;}
			else{
				servo[servoL] = 128;
			}
		}
	}
