	#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     touchSensor,         sensorTouch)
#pragma config(Sensor, S3,     lightSensor,         sensorNone)
#pragma config(Sensor, S4,     sonarSensor,         sensorNone)
#pragma config(Motor,  motorA,          gripperMotor,  tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorright,    tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorleft,     tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorrack,     tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorpicker,   tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorclamp,    tmotorNone, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorItreads,  tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This is for the NXT model, not TETRIX

/************************************\
|*  ROBOTC Virtual World            *|
|*                                  *|
|*  DO NOT OVERWRITE THIS FILE      *|
|*  MAKE SURE TO "SAVE AS" INSTEAD  *|
\************************************/
// The robot will move towards and hit the crate depending on the encoder target value

const int speed = -50;
const int pause = 1500;

void goStraight() {
  nMotorEncoder(motorD) = 0;
  nMotorEncoder(motorE) = 0;
  while (nMotorEncoder(motorD) <7500 && nMotorEncoder(motorE) < 7500) {
    motor[motorD] = speed;
    motor[motorE] = speed;
  }
}

void pauseBot() {
  motor[motorD] = 0;
  motor[motorE] = 0;
  wait1Msec(pause);
}

void turnAround() {
  nMotorEncoder(motorD) = 0;
  nMotorEncoder(motorE) = 0;
  while (nMotorEncoder(motorD) < 1650 && nMotorEncoder(motorE) < 1650){
    motor[motorD] = -speed;
    motor[motorE] = speed;
  }
}

void goStraight2() {
  nMotorEncoder(motorD) = 0;
  nMotorEncoder(motorE) = 0;
  while (nMotorEncoder(motorD) < 2000 && nMotorEncoder(motorE) < 2000) {
    motor[motorD] = speed;
    motor[motorE] = speed;
  }
}

void turnAround2() {
  nMotorEncoder(motorD) = 0;
  nMotorEncoder(motorE) = 0;
  while (nMotorEncoder(motorD) < 700 && nMotorEncoder(motorE) < 700) {
    motor[motorD] = -speed;
    motor[motorE] = speed;
  }
}

  void goStraight3() {
  nMotorEncoder(motorD) = 0;
  nMotorEncoder(motorE) = 0;
  while (nMotorEncoder(motorD) < 17000 && nMotorEncoder(motorE) < 17000) {
    motor[motorD] = speed;
    motor[motorE] = speed;
  }
}



task main () {
  goStraight();
  pauseBot();
  turnAround();
  pauseBot();
  goStraight2();
  pauseBot();
  turnAround2();
  pauseBot();
  goStraight3();
}
