#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorDriveLeft1, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorDriveLeft2, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorDriveRight1, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorDriveRight2, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void move(int x, int y, int t)
{
	motor[motorD] = x;
	//motor[motorDriveLeft2] = x;
	motor[motorE] = y;
	//motor[motorDriveRight2] = y;
	wait1Msec(t);
}

task main()
{
  ClearTimer(T1);
	while(SensorValue[S2]!= 5)
	{
	motor[motorD] = 30;
	//motor[motorDriveLeft2] = 10;
	motor[motorE] = 30;
	//motor[motorDriveRight2] = 10;
	}

	  int z = time1(T1);
   	move(0,0,2000);
	//	move(50,-50,1000);
		//move(0,0, 1000);
		//move(-50,50,1000);
		move(-30,-30,z);
	  move(0,0, 1000);
}





	/*while(SensorValue[S2] != 1)
	{	motor[motorD] = 20;
		motor[motorE] = -20;
	}*/
