#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Light2,         sensorLightActive)
#pragma config(Sensor, S3,     Light,          sensorLightActive)
#pragma config(Motor,  mtr_S1_C1_1,     motorright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorarmright, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorleft,     tmotorTetrix, openLoop, reversed)
#pragma config(Sensor, S4,     Force,          sensorLightInactive)
#pragma config(Motor,  mtr_S1_C2_2,     motorarm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorH,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void turnon()
{
	motor(motorA)=50;
}


void turnoff()
{
	motor(motorA)=0;

}


task main()
{

while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick);


  if (joy1Btn(8))
  	{
  		if (joystick.joy1_y2 < 7 && joystick.joy1_y2 > -7)//Change Log: Created Dead zones for the two joysticks
   		{
      	motor[motorright]= 0;
    	}
    	else
    	{
    		motor[motorright]= joystick.joy1_y2/2;
   		}
   		if (joystick.joy1_y1 < 7 && joystick.joy1_y1 > -7)//Change Log: Created Dead zones for the two joysticks
   		{
      	motor[motorleft]= 0;
    	}
    	else
    	{
  			motor[motorleft]=joystick.joy1_y1/2;
  		}
  	}


  	else
    {
  		if (joystick.joy1_y2 < 7 && joystick.joy1_y2 > -7)//Change Log: Created Dead zones for the two joysticks
   		{
      	motor[motorright]= 0;
    	}
    	else
    	{
    		motor[motorright]= joystick.joy1_y2;
   		}
   		if (joystick.joy1_y1 < 7 && joystick.joy1_y1 > -7)//Change Log: Created Dead zones for the two joysticks
   		{
      	motor[motorleft]= 0;
    	}
    	else
    	{
  			motor[motorleft]=joystick.joy1_y1;
  		}
    }


 /*   if (joy2Btn(6))
    	{
    motor[motorarm] = -3*joystick.joy2_y2/2;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[motorarmright] = -3*joystick.joy2_y2/2;
      }*/
   if (joy2Btn(7))
     {
      if (joystick.joy2_y2 < 7 && joystick.joy2_y2 > -7)//Change Log: Created Dead zones for the two joysticks
   		{
      	motor[motorarm]= 0;
      	motor[motorarmright]=0;
    	}
    	else
    	{
    		motor[motorarm]= joystick.joy2_y2;
    		motor[motorarmright]= joystick.joy2_y2;
   		}
		 }
    else
      {
    	  if (joystick.joy2_y2 < 7 && joystick.joy2_y2 > -7)//Change Log: Created Dead zones for the two joysticks
   			{
    	  	motor[motorarm]= 0;
   		   	motor[motorarmright]=0;
   		 	}
    		else
    		{
    			motor[motorarm] = joystick.joy2_y2;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
   				motor[motorarmright] = joystick.joy2_y2;
     		}
			}

    //}
    // motor[motorH] = joystick.joy2_x2;
    // BUd 6... 5=up, 6=down
   /*if ( joy2Btn (6))
    	{
    ClearTimer(T1);
while (time1(T1) <200)
	  {
    motor[motorarm] = -15;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[motorarmright] = -15;
    }
     motor[motorarm] = 0;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[motorarmright] = 0;

   }





    if ( joy2Btn (8))
    	{
    ClearTimer(T1);
while (time1(T1) <200)
	  {
    motor[motorarm] = 15;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[motorarmright] = 15;
    }
       motor[motorarm] = 0;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[motorarmright] = 0;
   }*/



   if ( joy1Btn (6))
    	{
    	 motor(motorH)= 65;
    //	 wait1Msec(100);
    //	 motor(motorH)= 0;
    	}
			else
				{
    		if ( joy1Btn (5))
    		{
    		motor(motorH)= -65;
    	//	wait1Msec(100);
    	//	motor(motorH)= 0;
    		}
				else
					{
						motor(motorH)= 0;
					}
			}


  /* if ( joy1Btn (6))
    	{
    	 motor(motorH)= 25;
    	 wait1Msec(100);
    	 motor(motorH)= 0;
    }
    if ( joy1Btn (5))
    	{
    		motor(motorH)= -25;
    		wait1Msec(100);
    		motor(motorH)= 0;
    	}*/


    	if (joy2Btn(1))
     {
      while(SensorValue(Light)<40)
      {
      	motor(motorarm)=50;
      	motor(motorarmright)=50;
      }


      	motor(motorarm)=0;
      	motor(motorarmright)=0;
    }


       	if (joy2Btn(2))
     {
      while(SensorValue(Light)<40)
      {
      	motor(motorarm)=-50;
      	motor(motorarmright)=-50;
      }


      	motor(motorarm)=0;
      	motor(motorarmright)=0;
    }


    	if (joy2Btn(3))
     {
      while(SensorValue(Light2)<40)
      {
      	motor(motorarm)=50;
      	motor(motorarmright)=50;
      }


      	motor(motorarm)=0;
      	motor(motorarmright)=0;
    }






   if (SensorValue(Force)>30)
   {
     turnon();
   }
    else
    {
    	turnoff();
    }



  }
}
