#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     Touch1,         sensorTouch)
#pragma config(Sensor, S3,     Touch2,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Tetrix Simple Tank Drive -                                        *|
|*                                          ROBOTC on Tetrix                                              *|
|*                                                                                                        *|
|*  This program allows you to drive a robot via remote control using the ROBOTC Debugger.                *|
|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port D                  motorD              12V                 Right motor                         *|
|*    Port E                  motorE              12V                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/

#include "JoystickDriver.c"

task main()
{
 while(true)                            // Infinite loop:
  {
 getJoystickSettings(joystick);

 if(joystick.joy1_y1<-10)
 {
    if(SensorValue(Touch1) == 1)
     {
     motor[motorD]=0;
     motor[motorE]=0;
    }
   else
    {
    motor[motorD] = joystick.joy1_y1;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[motorE] = -joystick.joy1_y1
    }
 }

 if(joystick.joy1_y1>10)
   {
   if(SensorValue(Touch2)== 1)
     {
	 motor[motorD] = 0;
	 motor[motorE] = 0;
     }
   else
     {
   motor[motorD] = joystick.joy1_y1;        // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
   motor[motorE] = -joystick.joy1_y1;
     }
   }

 if(joystick.joy1_y1<10 && joystick.joy1_y1>-10)
 {
   motor(motorD)=0;
   motor(motorE)=0;
}
   // Motor E is assigned a power level equal to the left analog stick's Y-axis reading.
/*else
{
	motor[motorD] =0;
	motor[motorE]=0;


    // BUTTONS TO CONTOL SERVO ARM
    // Control arm via shoulder buttons, 5 and 6... 5=up, 6=down
}*/
}
}
