#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S2,     touchmux,       sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define mux_button1 0x01
#define mux_button2 0x02
#define mux_button3 0x04
#define mux_button4 0x08


task main()
{
while(true)
{

if(SensorValue(touchmux) & mux_button1)
{
motor(motorD)=0;
}
else if(SensorValue(touchmux) & mux_button2)
{
motor(motorD)=0;
}
else
{
	motor(motorD)=50;
}



}
}
