#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Touch1,         sensorTouch)
#pragma config(Sensor, S3,     Touch2,         sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorArmLeft,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorArmRight, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorDriveLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorDriveRight, tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int speed = 50;


task main()
{
ClearTimer(T1);
while (time1(T1) <1500)
	{
    motor[motorDriveLeft] = 100;
    motor[motorDriveRight] = 100;
  }

clearTimer(T1);
  while (time1(T1) <750)
  	{
    motor[motorDriveLeft] = -speed;
    motor[motorDriveRight] = speed;
  }

 ClearTimer(T1);
while (time1(T1) <1000)
	{
   motor[motorDriveLeft] = speed;
    motor[motorDriveRight] = speed;
  }

  clearTimer(T1);
  while (time1(T1) <1000)
  	{
    motor[motorDriveLeft] = -speed;
    motor[motorDriveRight] = speed;
  }


   ClearTimer(T1);
  while (time1(T1) < 1000)
	{
   motor[motorDriveLeft] = speed;
    motor[motorDriveRight] = speed;
  }


  }
