#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTServo)
#pragma config(Sensor, S2,     Touch1,         sensorTouch)
#pragma config(Sensor, S3,     IR2,            sensorHiTechnicIRSeeker600)
#pragma config(Motor,  mtr_S1_C1_1,     motorArmLeft,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorArmRight, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorDriveLeft, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorDriveRight, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorArmUp,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C4_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C4_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C4_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Tetrix Simple Tank Drive -                                        *|
|*                                          ROBOTC on Tetrix                                              *|
|*                                                                                                        *|
|*  This program allows you to drive a robot via remote control using the ROBOTC Debugger.                *|
|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port D                  motorD              12V                 Right motor                         *|
|*    Port E                  motorE              12V                 Left motor                          *|
\*--------------------------------------------------------------------------------------------------------*/

#include "JoystickDriver.c"

task main()
{
	while(SensorValue(IR2)<5)
	{
		motor(motorDriveLeft)=50;
		motor(motorDriveRight)=-50;
  }
   	motor(motorDriveLeft)=0;
		motor(motorDriveRight)=0;
		wait1Msec(1000);

   	motor(motorDriveLeft)=50;
		motor(motorDriveRight)=50;
		wait1Msec(1000);


  	motor(motorDriveLeft)=0;
		motor(motorDriveRight)=0;

	}

