#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     touchmux,       sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     motorArm,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorFlag,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     motorBucket,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorArmUp,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_1,     motorDriveRight1, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorDriveRight2, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorDriveLeft1, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C4_2,     motorDriveLeft2, tmotorTetrix, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Tetrix Simple Tank Drive -                                        *|
|*                                          ROBOTC on Tetrix                                              *|
|*                                                                                                        *|
|*  This program allows you to drive a robot via remote control using the ROBOTC Debugger.                *|
|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port D                  motorD              12V                 Right motor                         *|
|*    Port E                  motorE              12V                 Left motor                          *|
\*--------------------------------------------------------------------------------------------------------*/


#define mux_button1 0x01
#define mux_button2 0x02
#define mux_button3 0x04
#define mux_button4 0x08


void move(int x, int y, int t)
{
	motor[motorDriveLeft1] = x;
	motor[motorDriveLeft2] = x;
	motor[motorDriveRight1] = y;
	motor[motorDriveRight2] = y;
	wait1Msec(t);
	motor[motorDriveLeft1] = 0;
	motor[motorDriveLeft2] = 0;
	motor[motorDriveRight1] = 0;
	motor[motorDriveRight2] = 0;
  wait1Msec(100);
}



void move2(int x, int y, int t)
{
	motor[motorDriveLeft1] = x;
	motor[motorDriveLeft2] = x;
	motor[motorDriveRight1] = y;
	motor[motorDriveRight2] = y;
	motor[motorArm]=-100;
	wait1Msec(t);
	motor[motorDriveLeft1] = 0;
	motor[motorDriveLeft2] = 0;
	motor[motorDriveRight1] = 0;
	motor[motorDriveRight2] = 0;
	motor[motorArm]=0;
  wait1Msec(100);
}

void moveArm(int x, int t)
{
	motor(motorArm)=x;
	wait1Msec(t);
	motor(motorArm)=0;
  wait1Msec(100);
}

void moveArmUp(int x, int t)
{
	motor(motorArmUp)=x;
	wait1Msec(t);
  	motor(motorArmUp)=0;
  wait1Msec(100);

}


void moveBucket(int x, int t)
{

	motor[motorBucket] = x;
	wait1Msec(t);
	motor[motorBucket]= 0;
	wait1Msec(100);
}


task main()
{


moveArm(100,6500);
moveArmUp(50,1200);
move(30,30,1700);
  moveBucket(30,1500);
  move(-50,-50, 700);
  move2(-90,90,700);
  move2(50,50,1500);
  move2(90,-90,700);
 move2(50,50,2050);
 moveArmUp(-50,1200);

}
