#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     Arm,           tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Gripper,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     ArmLower,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     Flag,          tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                    - Tetrix Simple Tank Drive -                                        *|
|*                                          ROBOTC on Tetrix                                              *|
|*                                                                                                        *|
|*  This program allows you to drive a robot via remote control using the ROBOTC Debugger.                *|
|*  This particular method uses "Tank Drive" where each side is controlled individually like a tank.      *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port D                  motorD              12V                 Right motor                         *|
|*    Port E                  motorE              12V                 Left motor                          *|
\*---------------------------------------------------------------------------------------------------4246-*/

#include "JoystickDriver.c"

task main()
{
  while(true)                            // Infinite loop:
  {
    getJoystickSettings(joystick);

    motor[motorD] = joystick.joy1_y1;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
    motor[motorE] = joystick.joy1_y2;         // Motor E is assigned a power level equal to the left analog stick's Y-axis reading.
		motor[Arm]=joystick.joy2_y1/2;

		if(joy2Btn(4))//if left bumper pressed
		{
			motor[Gripper]=-90;
		}
		else{motor[Gripper]=0;}

		if(joy2Btn(5))
		{
			motor[Gripper]=90;
			}
else
	{
	motor[Gripper]=0;
	}
//if(joy2Btn(5))//if right bumper is pressed
	//		{
		//		motor[Gripper]=-90;
		//	}else
			//	{motor[Gripper]=0;}

		motor[ArmLower]=joystick.joy2_y2;			//arm lowering motors are===driver 2 analog 2 Y axis
if(joy2Btn(3))			//if Y is pressed
{
	motor[Flag]=100;
}
else{motor[Flag]=0;
}

    // BUTTONS TO CONTOL SERVO ARM
    // Control arm via shoulder buttons, 5 and 6... 5=up, 6=down

  //  if(joy1Btn(5))          // If Button 5 is pressed:
  //  {
 //     servo[servo1] = 200;      // Raise Servo 1 to position 200.
 //   }

//    if(joy1Btn(6))          // If Button 6 is pressed:
  //  {
    //  servo[servo1] = 20;       // Lower Servo 1 to position 20.
    //}

  }
}
